eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: service_zuul

#进行路由映射配置
zuul:
  routes:
    api-a:
      path: /api-a/*
      serviceId: service_ribbon
    api-b:
      path: /api-b/*
      serviceId: service_feign